# Generated by Django 2.2.10 on 2020-03-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
