# Generated by Django 2.2.10 on 2020-03-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_shop', '0002_producto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='url',
            field=models.CharField(default='/', max_length=200),
        ),
    ]
