# Generated by Django 2.2.10 on 2020-03-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_shop', '0004_auto_20200309_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('articulo', models.IntegerField(default=0)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
