# Generated by Django 2.2.10 on 2020-03-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_shop', '0005_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='articulo',
            field=models.CharField(max_length=50),
        ),
    ]
